### PR TITLE
CLDCONNECT-2405: Repository ID can be dynamically set using Mule MEL …

### PR DESCRIPTION
**Pull request by karthikanantha**
…expression.

### CODE REVIEW

**Comment by sandipanbasu** [comment]
Looks good. Did you add (or update) the system test case for this change ?

**Comment by karthikanantha** [comment]
I have tested it manually in Studio, Since the old tests are obsolete now, I will add the system test cases during the migration to new CTF.

**Comment by sandipanbasu** [comment]
As discussed, please add the system test cases with this PR.

**Comment by sandipanbasu** [comment]
With the understanding that, this tests needs to be migrated to new CTF, looks good to me !!

**Pull request merged**
